version: '3'

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: amadeus161/foodgram_backend
    env_file: .env
    volumes:
      - static:/app/backend_static/
      - media:/app/media/
    depends_on:
      - db
  frontend:
    image: amadeus161/foodgram_frontend
    env_file: .env
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  nginx:
    image: amadeus161/foodgram_gateway
    env_file: .env
    depends_on:
      - backend
      - frontend
    ports:
      - 8000:80
    volumes:
      - static:/etc/nginx/html/static/
      - media:/etc/nginx/html/media/

volumes:
  pg_data:
  static:
  media:
