# Generated by Django 3.2.3 on 2024-01-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_is_not_author',
        ),
    ]
